# Generated by Django 2.0.4 on 2018-05-30 01:47

from django.db import migrations


def colleges(apps, schema_editor):
    College = apps.get_model("jwc", "College")
    db_alias = schema_editor.connection.alias
    College.objects.using(db_alias).bulk_create([
        College(name='计算机工程与科学', address='东区2号楼', tel='86050002'),
        College(name='通信与信息工程', address='东区3号楼', tel='86050003'),
        College(name='材料科学与工程', address='东区1号楼', tel='86050001'),
        College(name='机电工程与自动化', address='东区4号楼', tel='86050004'),
        College(name='环境与化学工程', address='东区5号楼', tel='86050005'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(colleges),
    ]
