# Generated by Django 2.0.4 on 2018-05-30 03:11

from django.db import migrations


def semesters(apps, schema_editor):
    Semester = apps.get_model("jwc", "Semester")
    db_alias = schema_editor.connection.alias
    Semester.objects.using(db_alias).bulk_create([
        Semester(year='17-18', season='autumn', start_date='2017-09-11', end_date='2017-12-10'),
        Semester(year='17-18', season='winter', start_date='2017-12-11', end_date='2018-03-25'),
        Semester(year='17-18', season='spring', start_date='2018-03-26', end_date='2018-06-17'),
        Semester(year='17-18', season='summer', start_date='2018-06-18', end_date='2018-08-26'),
        Semester(year='18-19', season='autumn', start_date='2018-09-11', end_date='2018-12-10'),
        Semester(year='18-19', season='winter', start_date='2018-12-11', end_date='2019-03-25'),
        Semester(year='18-19', season='spring', start_date='2019-03-26', end_date='2019-06-17'),
        Semester(year='18-19', season='summer', start_date='2019-06-18', end_date='2019-08-26'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('jwc', '0002_auto_20180530_0947'),
    ]

    operations = [
        migrations.RunPython(semesters),
    ]
